---
vagrantfile-local:
    # Virtual Machine configuration
    vm:
        # Box to use
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        # Hostname of the box (leave empty if unsure)
        hostname: 'vagrant.up'
        # Enable box auto-check for updates (recommended: on)
        box_check_update: true
        # Network setup
        network:
            # Enable public (bridged) network?
            public_network: '1'
            # Private network IP address
            private_network: 192.168.64.3
            # Forwarded ports
            forwarded_port: {  }
        # Memory, in Mb
        memory: '512'
        # Virtual CPUs
        cpus: '1'
        # A message to show after vagrant up
        post_up_message: ''
        # Provider configuration
        provider:
            # Settings for VirtualBox
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
    # SSH configuration
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    # Configure PHP versions to install
    multiphp:
        # For each PHP version we have a phpXY entry where X.Y is the Major.Minor version of PHP to install
        php53:
            # Install this version of PHP?
            install: 1
            # Where to download the sources from? Make sure it is a /from/this/mirror URL from php.net, not /choose/a/mirror!!!
            source_url: http://de1.php.net/get/php-5.3.29.tar.bz2/from/this/mirror
            # Should I make it the default PHP version? Only set 1 version as the default or all hell will break lose
            default: 0
            # The hostname to use for this version of PHP
            hostname: vagrant53.up
            # Install XDebug?
            xdebug_install: 1
            # Where to download XDebug from? Yes, we allow different XDebug versions for each version of PHP.
            # WARNING: Do not change the download URLs for XDebug for PHP 5.3. XDebug 2.3 seems to only support PHP 5.4 and later (makes sense, PHP 5.3 is EOL)
            xdebug_url: http://xdebug.org/files/xdebug-2.2.7.tgz
        php54:
            install: 1
            source_url: http://de1.php.net/get/php-5.4.45.tar.bz2/from/this/mirror
            default: 1
            hostname: vagrant54.up
            xdebug_install: 1
            xdebug_url: http://xdebug.org/files/xdebug-2.3.3.tgz
        php55:
            install: 1
            source_url: http://de1.php.net/get/php-5.5.30.tar.bz2/from/this/mirror
            default: 0
            hostname: vagrant55.up
            xdebug_install: 1
            xdebug_url: http://xdebug.org/files/xdebug-2.3.3.tgz
        php56:
            install: 1
            source_url: http://de1.php.net/get/php-5.6.16.tar.bz2/from/this/mirror
            default: 0
            hostname: vagrant56.up
            xdebug_install: 1
            xdebug_url: http://xdebug.org/files/xdebug-2.3.3.tgz
        php70:
            install: 1
            source_url: http://de1.php.net/get/php-7.0.0.tar.bz2/from/this/mirror
            default: 0
            hostname: vagrant70.up
            xdebug_install: 1
            xdebug_url: http://xdebug.org/files/xdebug-2.4.0rc3.tgz
    extrascripts:
        phpmyadmin:
            install: 1
            source_url: https://files.phpmyadmin.net/phpMyAdmin/4.5.1/phpMyAdmin-4.5.1-english.zip
        pml:
            install: 1
            source_url: https://github.com/potsky/PimpMyLog/tarball/master